export interface Listing {
  id: string
  images: string[]
  title: string
  address: string
  price: number
  bedrooms: number
  bathrooms: number
  style: string
  offer: string | null
  prices: { beds: number; price: number }[]
  location: string
  type: string
  description?: string
  amenities?: string[]
}

export const SAMPLE_LISTINGS: Listing[] = [
  // Homes for Rent
  {
    id: "1",
    images: ["/modern-apartment-living-room.png", "/modern-apartment-kitchen.png", "/cozy-apartment-bedroom.png"],
    title: "NOVO New Hampstead",
    address: "480 John Carter Rd, Chapel Hill",
    price: 1575,
    bedrooms: 1,
    bathrooms: 1,
    style: "Wood-style flooring",
    offer: "12 available units",
    location: "Chapel Hill",
    type: "Home",
    prices: [
      { beds: 1, price: 1575 },
      { beds: 2, price: 1950 },
      { beds: 3, price: 2350 },
    ],
    description: "Modern home with wood-style flooring and premium amenities.",
    amenities: ["WiFi", "Gym", "Parking", "Pool", "Laundry"],
  },
  {
    id: "2",
    images: ["/luxury-modern-living-room-with-fireplace-and-woode.jpg", "/cozy-living-room.png", "/cozy-backyard.png"],
    title: "RENDER Turner Lake",
    address: "by Crescent Communities, Raleigh",
    price: 1584,
    bedrooms: 1,
    bathrooms: 1,
    style: "Sleek urban design",
    offer: "Special Offer",
    location: "Raleigh",
    type: "Home",
    prices: [
      { beds: 1, price: 1584 },
      { beds: 2, price: 1925 },
      { beds: 3, price: 2309 },
    ],
    description: "Sleek urban home with modern amenities in a prime location.",
    amenities: ["WiFi", "Gym", "Concierge", "Security", "Smart Home"],
  },
  {
    id: "3",
    images: ["/modern-apartment-with-kitchen-and-dining-area.jpg", "/studio-kitchen.jpg", "/studio-bathroom.jpg"],
    title: "Downtown Modern",
    address: "123 Main St, Durham",
    price: 1650,
    bedrooms: 1,
    bathrooms: 1,
    style: "Modern amenities",
    offer: "Special Offer",
    location: "Durham",
    type: "Home",
    prices: [
      { beds: 1, price: 1650 },
      { beds: 2, price: 2000 },
      { beds: 3, price: 2400 },
    ],
    description: "Modern home with state-of-the-art amenities.",
    amenities: ["Utilities Included", "Furnished", "Pet Friendly", "WiFi"],
  },
  {
    id: "4",
    images: [
      "/modern-apartment-living-room-with-wood-flooring.jpg",
      "/cozy-studio-apartment.png",
      "/spacious-house-exterior.jpg",
    ],
    title: "Chapel Hill Residences",
    address: "95 University Dr, Chapel Hill",
    price: 1495,
    bedrooms: 1,
    bathrooms: 1,
    style: "Student-friendly",
    offer: null,
    location: "Chapel Hill",
    type: "Home",
    prices: [
      { beds: 1, price: 1495 },
      { beds: 2, price: 1795 },
      { beds: 3, price: 2195 },
    ],
    description: "Student-friendly home near campus.",
    amenities: ["WiFi", "Parking", "Laundry", "Community Space"],
  },
  {
    id: "5",
    images: ["/luxury-modern-living-room-with-fireplace-and-woode.jpg", "/cozy-living-room.png", "/cozy-backyard.png"],
    title: "Raleigh Downtown Lofts",
    address: "234 Fayetteville St, Raleigh",
    price: 1725,
    bedrooms: 1,
    bathrooms: 1,
    style: "Industrial chic",
    offer: "Special Offer",
    location: "Raleigh",
    type: "Home",
    prices: [
      { beds: 1, price: 1725 },
      { beds: 2, price: 2150 },
      { beds: 3, price: 2600 },
    ],
    description: "Industrial chic home in downtown Raleigh with exposed brick.",
    amenities: ["Rooftop Deck", "Gym", "Bike Storage", "Pet Friendly"],
  },
  {
    id: "6",
    images: ["/spacious-house-exterior.jpg", "/cozy-living-room.png", "/cozy-backyard.png"],
    title: "Sunny Valley House",
    address: "456 Oak Lane, Chapel Hill",
    price: 2100,
    bedrooms: 3,
    bathrooms: 2,
    style: "Traditional home",
    offer: "New listing",
    location: "Chapel Hill",
    type: "Home",
    prices: [
      { beds: 2, price: 1950 },
      { beds: 3, price: 2100 },
      { beds: 4, price: 2500 },
    ],
    description: "Beautiful traditional home with large backyard.",
    amenities: ["Garage", "Yard", "Porch", "Storage"],
  },
  {
    id: "7",
    images: ["/modern-apartment-kitchen.png", "/cozy-studio-apartment.png", "/modern-apartment-living-room.png"],
    title: "Riverside Condo Complex",
    address: "789 River Rd, Durham",
    price: 1850,
    bedrooms: 2,
    bathrooms: 2,
    style: "Contemporary design",
    offer: null,
    location: "Durham",
    type: "Home",
    prices: [
      { beds: 1, price: 1650 },
      { beds: 2, price: 1850 },
      { beds: 3, price: 2200 },
    ],
    description: "Contemporary home with river views and modern finishes.",
    amenities: ["River View", "Fitness Center", "Parking", "Security"],
  },
  {
    id: "8",
    images: [
      "/cozy-apartment-bedroom.png",
      "/modern-apartment-kitchen.png",
      "/luxury-modern-living-room-with-fireplace-and-woode.jpg",
    ],
    title: "Hillside Apartments",
    address: "321 Hill St, Raleigh",
    price: 1425,
    bedrooms: 1,
    bathrooms: 1,
    style: "Cozy spaces",
    offer: null,
    location: "Raleigh",
    type: "Home",
    prices: [
      { beds: 1, price: 1425 },
      { beds: 2, price: 1750 },
      { beds: 3, price: 2100 },
    ],
    description: "Cozy home in a quiet hillside neighborhood.",
    amenities: ["WiFi", "Laundry", "Parking", "Garden"],
  },
  {
    id: "9",
    images: ["/spacious-house-exterior.jpg", "/cozy-backyard.png", "/cozy-living-room.png"],
    title: "Green Meadows Estate",
    address: "555 Forest Ave, Chapel Hill",
    price: 2450,
    bedrooms: 4,
    bathrooms: 3,
    style: "Luxury estate",
    offer: "Premium property",
    location: "Chapel Hill",
    type: "Home",
    prices: [
      { beds: 3, price: 2250 },
      { beds: 4, price: 2450 },
      { beds: 5, price: 2850 },
    ],
    description: "Luxurious home with extensive grounds and high-end finishes.",
    amenities: ["Pool", "Garage", "Garden", "Patio", "Security System"],
  },
  {
    id: "10",
    images: ["/modern-apartment-living-room.png", "/studio-kitchen.jpg", "/cozy-apartment-bedroom.png"],
    title: "Park View Condominiums",
    address: "678 Park Blvd, Durham",
    price: 1920,
    bedrooms: 2,
    bathrooms: 2,
    style: "Park-facing view",
    offer: "Special Offer",
    location: "Durham",
    type: "Home",
    prices: [
      { beds: 1, price: 1750 },
      { beds: 2, price: 1920 },
      { beds: 3, price: 2300 },
    ],
    description: "Park-facing home with modern amenities and great views.",
    amenities: ["Park View", "Concierge", "Gym", "Pool"],
  },
  {
    id: "11",
    images: ["/cozy-studio-apartment.png", "/modern-apartment-kitchen.png", "/cozy-apartment-bedroom.png"],
    title: "Urban Core Apartments",
    address: "999 Central Ave, Raleigh",
    price: 1550,
    bedrooms: 1,
    bathrooms: 1,
    style: "Downtown living",
    offer: "Move-in Special",
    location: "Raleigh",
    type: "Home",
    prices: [
      { beds: 1, price: 1550 },
      { beds: 2, price: 1900 },
      { beds: 3, price: 2300 },
    ],
    description: "Downtown home in the heart of the city.",
    amenities: ["WiFi", "Rooftop Lounge", "Security", "Concierge"],
  },
  {
    id: "12",
    images: [
      "/luxury-modern-living-room-with-fireplace-and-woode.jpg",
      "/spacious-house-exterior.jpg",
      "/cozy-backyard.png",
    ],
    title: "Countryside Manor",
    address: "111 Country Lane, Chapel Hill",
    price: 2200,
    bedrooms: 3,
    bathrooms: 2.5,
    style: "Rural charm",
    offer: null,
    location: "Chapel Hill",
    type: "Home",
    prices: [
      { beds: 2, price: 2000 },
      { beds: 3, price: 2200 },
      { beds: 4, price: 2600 },
    ],
    description: "Charming countryside home with character and space.",
    amenities: ["Acreage", "Barn", "Well", "Pond"],
  },

  // Shortlets
  {
    id: "13",
    images: ["/modern-apartment-living-room.png", "/modern-apartment-kitchen.png", "/cozy-apartment-bedroom.png"],
    title: "Luxury Shortlet - Chapel Hill",
    address: "450 Ridge Rd, Chapel Hill",
    price: 120,
    bedrooms: 2,
    bathrooms: 2,
    style: "Modern luxury",
    offer: "Nightly rates",
    location: "Chapel Hill",
    type: "Shortlet",
    prices: [
      { beds: 1, price: 85 },
      { beds: 2, price: 120 },
    ],
    description: "Luxurious short-term rental with full amenities.",
    amenities: ["WiFi", "Kitchen", "AC", "Smart TV", "Washer/Dryer"],
  },
  {
    id: "14",
    images: ["/cozy-living-room.png", "/cozy-backyard.png", "/modern-apartment-living-room.png"],
    title: "Urban Shortlet - Raleigh",
    address: "567 Main St, Raleigh",
    price: 110,
    bedrooms: 1,
    bathrooms: 1,
    style: "Urban chic",
    offer: "Weekly discount",
    location: "Raleigh",
    type: "Shortlet",
    prices: [{ beds: 1, price: 110 }],
    description: "Urban chic shortlet in the heart of Raleigh.",
    amenities: ["WiFi", "Kitchenette", "Parking", "Gym Access"],
  },
  {
    id: "15",
    images: ["/studio-kitchen.jpg", "/studio-bathroom.jpg", "/modern-apartment-with-kitchen-and-dining-area.jpg"],
    title: "Cozy Shortlet - Durham",
    address: "234 Home Rd, Durham",
    price: 95,
    bedrooms: 1,
    bathrooms: 1,
    style: "Cozy comfort",
    offer: null,
    location: "Durham",
    type: "Shortlet",
    prices: [{ beds: 1, price: 95 }],
    description: "Cozy and comfortable short-term rental perfect for travelers.",
    amenities: ["WiFi", "Full Kitchen", "Linens Included", "Coffee Maker"],
  },
  {
    id: "16",
    images: [
      "/luxury-modern-living-room-with-fireplace-and-woode.jpg",
      "/cozy-living-room.png",
      "/modern-apartment-kitchen.png",
    ],
    title: "Premium Shortlet - Chapel Hill",
    address: "789 Luxury Lane, Chapel Hill",
    price: 150,
    bedrooms: 3,
    bathrooms: 2,
    style: "Premium experience",
    offer: "Monthly rates available",
    location: "Chapel Hill",
    type: "Shortlet",
    prices: [
      { beds: 2, price: 130 },
      { beds: 3, price: 150 },
    ],
    description: "Premium shortlet with high-end furnishings and services.",
    amenities: ["WiFi", "Full Kitchen", "Concierge", "Pool Access", "Parking"],
  },
  {
    id: "17",
    images: ["/cozy-studio-apartment.png", "/modern-apartment-living-room.png", "/studio-kitchen.jpg"],
    title: "Budget Shortlet - Raleigh",
    address: "456 Economy Ave, Raleigh",
    price: 75,
    bedrooms: 1,
    bathrooms: 1,
    style: "Budget friendly",
    offer: "Best rates",
    location: "Raleigh",
    type: "Shortlet",
    prices: [{ beds: 1, price: 75 }],
    description: "Budget-friendly shortlet without compromising on comfort.",
    amenities: ["WiFi", "Basic Kitchen", "Fan", "Shared Lounge"],
  },

  // Hostels
  {
    id: "18",
    images: ["/cozy-living-room.png", "/cozy-backyard.png", "/modern-apartment-living-room.png"],
    title: "Central Hostel - Chapel Hill",
    address: "101 Main St, Chapel Hill",
    price: 35,
    bedrooms: 1,
    bathrooms: 1,
    style: "Social atmosphere",
    offer: "Dorm beds available",
    location: "Chapel Hill",
    type: "Hostel",
    prices: [{ beds: 1, price: 35 }],
    description: "Social hostel with communal areas and local travelers.",
    amenities: ["Free WiFi", "Common Kitchen", "Social Events", "Lockers", "Sheets Included"],
  },
  {
    id: "19",
    images: ["/modern-apartment-kitchen.png", "/cozy-studio-apartment.png", "/modern-apartment-living-room.png"],
    title: "Downtown Hostel - Raleigh",
    address: "222 Downtown Blvd, Raleigh",
    price: 40,
    bedrooms: 1,
    bathrooms: 1,
    style: "Prime location",
    offer: "Weekly passes",
    location: "Raleigh",
    type: "Hostel",
    prices: [{ beds: 1, price: 40 }],
    description: "Prime location hostel near all downtown attractions.",
    amenities: ["WiFi", "Breakfast Included", "Bike Rental", "Tour Desk", "Laundry"],
  },
  {
    id: "20",
    images: ["/studio-bathroom.jpg", "/studio-kitchen.jpg", "/modern-apartment-with-kitchen-and-dining-area.jpg"],
    title: "Budget Hostel - Durham",
    address: "333 Budget St, Durham",
    price: 30,
    bedrooms: 1,
    bathrooms: 1,
    style: "Affordable comfort",
    offer: "Lowest rates",
    location: "Durham",
    type: "Hostel",
    prices: [{ beds: 1, price: 30 }],
    description: "Most affordable hostel with clean rooms and friendly staff.",
    amenities: ["WiFi", "Shared Kitchen", "Common Area", "Lockers", "Basic Breakfast"],
  },
  {
    id: "21",
    images: ["/cozy-backyard.png", "/cozy-living-room.png", "/modern-apartment-living-room.png"],
    title: "Premium Hostel - Chapel Hill",
    address: "555 Premium Rd, Chapel Hill",
    price: 55,
    bedrooms: 1,
    bathrooms: 1,
    style: "Upscale hostel",
    offer: "Private rooms available",
    location: "Chapel Hill",
    type: "Hostel",
    prices: [{ beds: 1, price: 55 }],
    description: "Upscale hostel with premium amenities and private room options.",
    amenities: ["WiFi", "Full Kitchen", "Bar", "Lounge", "Free Breakfast", "Laundry"],
  },
  {
    id: "22",
    images: [
      "/luxury-modern-living-room-with-fireplace-and-woode.jpg",
      "/modern-apartment-kitchen.png",
      "/cozy-apartment-bedroom.png",
    ],
    title: "Traveler's Hostel - Raleigh",
    address: "666 Traveler Way, Raleigh",
    price: 45,
    bedrooms: 1,
    bathrooms: 1,
    style: "Travel hub",
    offer: "Group discounts",
    location: "Raleigh",
    type: "Hostel",
    prices: [{ beds: 1, price: 45 }],
    description: "Popular travel hub with activities and day trips organized.",
    amenities: ["WiFi", "Kitchen", "Lounge", "Event Calendar", "Tour Booking"],
  },
]
